= Die Wolken

:hp-tags: Imam Mahdi, Betrübnis, Sorgen, Wolken


Wenn die Wolken die Sonne bedecken, die Winde stark wehen. Wenn alles in Dunkelheit eingehüllt wird, dann ist der Mensch so betrübt. Aber gebe es diese Wolken nicht, würde sich der Mensch nicht nach der Sonne sehnen. Man darf auch nicht vergessen, dass erst durch diese Wolken der Mensch, die Tiere und Pflanzen wachsen können. Wir brauchen die Wolken, die anschließend niederfallen und im Zusammenspiel mit der Sonne alles wachsen lassen. 
Sind die Sorgen, die wir haben denn nicht vergleichbar mit den Wolken? Erst wenn wir Sorge und Kummer haben, sehnen wir uns nach der Sonne. Diese Sehnsucht ist auch eine Sehnsucht nach dem Wachstum, eine Sehnsucht nach Entwicklung. Wir hoffen, dass diese Sorgen bald verschwinden, wir unsere Nutzen von diesen Sorgen und Prüfungen ziehen, um auch anschließend die Sonne, also den Imam zu erkennen, damit wir von ihm profitieren können. 
Wir müssen dankbar für jede Wolke sein, die zu unserem Wachstum beiträgt- die in uns die Sehnsucht nach der Sonne weckt. 


