= 5-stündiges Treffen von Studenten mit Imam Khamenei

:hp-tags: Treffe, Studenten, Imam


- Die eigentliche Ursache der Feindseligkeiten der Gewaltherrscher gegenüber der iranischen Nation liegt in der Ablehnung dieses Gewaltsystems durch Iran.
- Wer in diesem Frühling der Spiritualität und Reinheit sein Herz dem Segen und Gnade Gottes aussetzt, wird in Zukunft die süßen Früchte dieses Saatgutes groß nutzen. (Monat Ramadan) 
 Ayatollah Khamenei nannte den erstaunlichen Einfluss und die Präsenz  Irans in der Region eine Tatsache, die studentische Vereine hochschätzen sollten. Man sei darüber informiert, dass die Amerikaner und Rückständigen in der Region bei Geheimsitzungen gegen diesen Einfluss Pläne schmieden, aber doch nichts ausrichten können. Das geehrte Staatsoberhaupt wies auf die hunderttägige Bombardierung Jemens und barbarische Massaker am unschuldigen Volk dieses Landes hin und sagte: Der liberale Westen, der sich als Menschenrechtsverfechter  ausgibt, schweigt gegenüber Verbrechen der Saudis; der Sicherheitsrat hat in einem seiner schamlosesten Resolutionen die Angegriffenen statt Angreifer verurteilt. Der Grund für die Bombardierung der Wohngebiete im Jemen liege in der Bosheit und dem Zorn der Saudis und ihrer Unterstützer über den Einfluss Irans in der Region. Im Gegensatz zu den Behauptungen ist der Einfluss Irans in der Region eine göttliche und keine physikalische Gabe. Das geehrte Staatsoberhaupt gab den Studenten den Rat, die Entwicklungen in der Region und international, u.a. die Ereignisse im Jemen, Irak und in  Syrien eingehend zu untersuchen. Die Gründung studentischer Vereine zu Wahlzwecken sei eine Beleidigung solcher Institutionen. Abgesehen von diesen Einweg-Vereinen können islamische und interessierte Vereine bei einer allgemeinen Bewegung sehr nützlich und wirksam sein. Der Kampf gegen Imperialismus und Gewaltherrscher wird laut Lehren des Korans niemals ein Ende finden, heute sind die USA das deutlichste Beispiel für den Imperialismus. Dieser Kampf ist Teil der Revolutionsgrundsätze und des Fundaments, daher sollten sich die Studenten auf die Fortsetzung des Kampfes gegen den Imperialismus vorbereiten. Der geehrte Ayatollah Khamenei zählte die iranische Jugend zu den aktivsten, fröhlichsten und dynamischsten Jugendlichen der Welt. Im Gegenzug beweise die hohe Selbstmordrate unter europäischen Jugendlichen die Depression in der westlichen Welt. Die starke Neigung europäischer Jugendlichen, sich der Terrororganisation "Islamischer Staat"( IS) anzuschließen, um Selbstmordanschläge zu verüben, sei ein Beispiel für die Depression im Westen. Die iranischen Jugendlichen aber fasten, halten nächtliche Gebete in den Schicksalsnächten und nehmen trotz der großen Hitze an den Demonstrationen zum El-Kuds-Tag teil; sie sind dynamisch, fröhlich und sehr weit entfernt von Depression. 